"""Audit local native Steve texture/material candidates; never install a mod.

Run with Python 3.12 after prepare_steve_material.py. --rebuild adds a fresh
read-only native-template extraction and requires identical generated bytes.
Pillow in --decoder-python decodes all mips independently of our BC encoder.
"""
from __future__ import annotations

import argparse
import collections
import copy
import json
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest
from unittest import mock
import zlib

import prepare_native_steve as native
import prepare_steve_material as material


class SteveMaterialChecks(unittest.TestCase):
    output = native.ROOT / "build" / "steve-material"
    source = native.ROOT / "build" / "cdmw-fixed-source"
    deps = native.ROOT / "build" / "cdmw-deps"
    steve = native.ROOT / "build" / "steve-1.21.1"
    native_assets = native.ROOT / "build" / "native-steve"
    decoder_python = Path(shutil.which("python") or "python")
    rebuild = False

    @classmethod
    def setUpClass(cls) -> None:
        native.load_cdmw(cls.source, cls.deps)
        cls.report = json.loads((cls.output / "steve-material-report.json").read_text(encoding="utf-8"))
        cls.resources = cls.report["candidateResources"]
        cls.texture_rows = {r["virtualPath"]: r for r in cls.resources if r["kind"] == "texture"}
        cls.png = (cls.steve / "steve.png").read_bytes()
        width, height, pixels = material.decode_png(cls.png)
        cls.width, cls.height, cls.pixels = material.nearest_expand(width, height, pixels, 4)

    def test_01_fixed_source_and_templates(self) -> None:
        self.assertEqual(self.report["cdmw"]["commit"], native.CDMW_COMMIT)
        self.assertEqual(native.source_fingerprint(self.source), native.CDMW_SOURCE_SHA256)
        for path, expected, _fourcc, _size in material.TEXTURE_TEMPLATES.values():
            self.assertEqual(native.file_hash(self.output / "template" / path), expected)
        self.assertEqual(native.file_hash(self.output / "template" / material.SHADER_TEMPLATE), material.SHADER_TEMPLATE_SHA256)
        for name, expected in self.report["files"].items():
            self.assertEqual(native.file_hash(self.output / name), expected)

    def test_02_resource_plan_has_grounded_unique_paths(self) -> None:
        self.assertEqual(len(self.resources), 5)
        self.assertEqual(len({r["virtualPath"].casefold() for r in self.resources}), 5)
        self.assertEqual({r["virtualPath"] for r in self.resources}, set(material.TEXTURE_PATHS.values()) | {material.PAC_PATH, material.MATERIAL_PATH})
        for row in self.resources:
            self.assertIn("crimsonmc_", Path(row["virtualPath"]).name)
            local = self.output / row["localFile"]
            self.assertTrue(local.resolve().is_relative_to(self.output.resolve()))
            self.assertEqual(native.file_hash(local), row["sha256"])
            self.assertTrue(row["templatePath"])
            self.assertEqual(len(row["templateSha256"]), 64)
        pac = next(r for r in self.resources if r["kind"] == "skinnedMesh")
        self.assertEqual(pac["sha256"], material.CANDIDATE_PAC_SHA256)
        self.assertEqual(pac["templateSha256"], native.TEMPLATE_HASHES[native.BODY])
        self.assertEqual((self.output / pac["localFile"]).read_bytes(), (self.native_assets / "steve-rig-candidate.pac").read_bytes())

    def test_03_native_headers_preserve_opaque_template_metadata(self) -> None:
        from cdmw.core.dds_native import inspect_dds_native
        allowed = set(range(12, 48))
        for kind, (template_path, _sha, fourcc, _size) in material.TEXTURE_TEMPLATES.items():
            data = (self.output / self.texture_rows[material.TEXTURE_PATHS[kind]]["localFile"]).read_bytes()
            template = (self.output / "template" / template_path).read_bytes()
            self.assertEqual(bytes(b for i, b in enumerate(data[:128]) if i not in allowed),
                             bytes(b for i, b in enumerate(template[:128]) if i not in allowed))
            info = inspect_dds_native(data)
            self.assertFalse(info.reason)
            self.assertEqual((info.width, info.height, info.mip_count), (256, 256, 9))
            self.assertEqual(info.fourcc, fourcc)
            self.assertEqual(struct.unpack_from("<I", data, 24)[0], 1)
            self.assertEqual(struct.unpack_from("<4I", data, 32), tuple(m.byte_count for m in info.mip_levels[:4]))
            self.assertEqual(info.mip_levels[-1].offset + info.mip_levels[-1].byte_count, len(data))

    def test_04_official_indexed_png_matches_independent_decoder(self) -> None:
        decoder, [decoded] = material.independent_decode([self.png], self.decoder_python)
        self.assertEqual(decoder["version"], material.PILLOW_VERSION)
        self.assertEqual(decoder["ddsPluginSha256"], material.PILLOW_DDS_PLUGIN_SHA256)
        self.assertEqual(decoded, material.decode_png(self.png))
        alpha = collections.Counter(p[3] for p in decoded[2])
        self.assertGreater(alpha[0], 0)
        self.assertGreater(alpha[255], 0)

    def test_05_all_mips_independently_decode_and_report_real_loss(self) -> None:
        maps = {"base": self.pixels, "normal": [(128, 128, 255, 255)] * 65536,
                "material": [(0, 255, 0, 255)] * 65536}
        for kind, reference in maps.items():
            path, _sha, fourcc, _dim = material.TEXTURE_TEMPLATES[kind]
            data = (self.output / self.texture_rows[material.TEXTURE_PATHS[kind]]["localFile"]).read_bytes()
            decoder, audit = material.verify_texture(data, self.width, self.height, reference, fourcc, self.decoder_python)
            self.assertEqual(decoder, self.report["independentDecoder"])
            actual_report = copy.deepcopy(self.report["textures"][kind])
            self.assertEqual(actual_report.pop("templatePath"), path)
            actual_report.pop("templateLast4Preserved")
            # JSON object keys are strings; source alpha counts are numeric keys.
            self.assertEqual(json.loads(json.dumps(audit)), actual_report)
            self.assertEqual(len(audit["independentDecode"]), 9)
            self.assertEqual(audit["independentDecode"][0]["maxAlphaError"], 0)
        self.assertFalse(self.report["textureEncoding"]["lossless"])
        self.assertGreater(self.report["textures"]["base"]["independentDecode"][0]["maxRgbError"], 0)

    def test_06_all_body_variants_have_only_source_owned_plain_inputs(self) -> None:
        from cdmw.core.pac_xml_standard_material import find_material_wrappers
        row = next(r for r in self.resources if r["kind"] == "skinnedMaterial")
        data = (self.output / row["localFile"]).read_bytes()
        template = (self.native_assets / "template" / native.MATERIAL).read_bytes()
        donor = (self.output / "template" / material.SHADER_TEMPLATE).read_bytes()
        rebuilt, audit = material.material_candidate(template, donor)
        self.assertEqual(data, rebuilt)
        self.assertEqual(self.report["material"], audit)
        self.assertEqual(audit["wrappers"], 18)
        wrappers = find_material_wrappers(data.decode("utf-8"))
        self.assertEqual(collections.Counter(w.submesh_name for w in wrappers), {name: 6 for name in material.DRAW_NAMES})
        for wrapper in wrappers:
            self.assertEqual(wrapper.shader, "SkinnedMeshStandard")
            self.assertEqual({p.name for p in wrapper.parameters}, {"_baseColorTexture", "_normalTexture", "_materialTexture", "_renderSettingFlag"})
            self.assertEqual(wrapper.value("_renderSettingFlag"), "4")
        material.wrap_xml(data.decode("utf-8"))

    def test_07_pixel_codec_has_known_external_vectors(self) -> None:
        # Solid endpoints have known packed forms; Pillow's separate native BC
        # decoder verifies our endpoint order and per-channel bit conventions.
        for fourcc, color in (("DXT1", (255, 0, 0, 255)), ("DXT5", (0, 255, 0, 128)),
                              ("BC5U", (128, 128, 255, 255))):
            data = material.encode_dds(4, 4, [color] * 16, fourcc)
            _decoder, decoded = material.independent_decode(material.split_dds_mips(data), self.decoder_python)
            self.assertEqual(len(decoded), 3)
            self.assertEqual(decoded[0][2][0][:2], color[:2])
            if fourcc != "BC5U":
                self.assertEqual(decoded[0][2], [color] * 16)

    def test_08_unreviewed_formats_pixels_and_templates_stop(self) -> None:
        with self.assertRaisesRegex(ValueError, "opaque"):
            material.encode_dds(4, 4, [(1, 2, 3, 0)] * 16, "DXT1")
        for w, h, fourcc in ((3, 4, "DXT1"), (4, 4, "DX10"), (2048, 4, "DXT1")):
            with self.assertRaises(ValueError):
                material.encode_dds(w, h, [(1, 2, 3, 255)] * 16, fourcc)
        with self.assertRaises(ValueError):
            material.encode_dds(4, 4, [(1, 2, 3, 999)] * 16)
        with self.assertRaisesRegex(ValueError, "template"):
            material.encode_dds(4, 4, [(1, 2, 3, 255)] * 16, template_header=b"DDS " + b"\0" * 124)

    def test_09_corrupt_png_and_dds_stop(self) -> None:
        bad = bytearray(self.png)
        bad[-5] ^= 1
        with self.assertRaisesRegex(ValueError, "checksum"):
            material.decode_png(bytes(bad))
        bad = bytearray(self.png)
        bad[24] = 16  # valid CRC but unsupported PNG bit depth
        struct.pack_into(">I", bad, 29, zlib.crc32(bad[12:29]) & 0xFFFFFFFF)
        with self.assertRaisesRegex(ValueError, "noninterlaced"):
            material.decode_png(bytes(bad))
        with self.assertRaises(ValueError):
            material.decode_png(self.png + b"trailing")
        data = (self.output / self.texture_rows[material.TEXTURE_PATHS["base"]]["localFile"]).read_bytes()
        for bad_dds in (data[:-1], data + b"trailing"):
            with self.assertRaises(ValueError):
                material.split_dds_mips(bad_dds)

    def test_10_unknown_material_template_stops_before_rewrite(self) -> None:
        template = (self.native_assets / "template" / native.MATERIAL).read_bytes()
        donor = (self.output / "template" / material.SHADER_TEMPLATE).read_bytes()
        with self.assertRaisesRegex(ValueError, "fingerprint"):
            material.material_candidate(template + b" ", donor)
        with self.assertRaisesRegex(ValueError, "fingerprint"):
            material.material_candidate(template, donor + b" ")

    def test_11_no_resource_loading_or_native_behavior_claims(self) -> None:
        self.assertTrue(self.report["integration"])
        self.assertTrue(all(value is False for value in self.report["integration"].values()))
        self.assertFalse(self.report["material"]["alphaBehaviorVerified"])
        self.assertTrue(any("PATHC" in line for line in self.report["limitations"]))
        self.assertTrue(any("no appearance/controller binding" in line for line in self.report["limitations"]))

    def test_12_output_protection_includes_report_and_relative_traversal(self) -> None:
        with self.assertRaises(ValueError):
            native.output_directory(native.ROOT / "artifacts" / "skin")
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="material_check_") as temporary:
            output = Path(temporary)
            with self.assertRaisesRegex(ValueError, "escapes"):
                material.publish(output, {"../escape.dds": b"asset"}, {})
            self.assertEqual(list(output.iterdir()), [])
            linked = output / "steve-material-report.json"
            original = Path.is_symlink
            with mock.patch.object(Path, "is_symlink", lambda p: p == linked or original(p)):
                with self.assertRaisesRegex(ValueError, "symlink"):
                    material.publish(output, {"first.dds": b"asset"}, {})
            self.assertEqual(list(output.iterdir()), [])

    def test_13_bytes_rebuild_from_the_exact_local_templates(self) -> None:
        maps = {"base": self.pixels, "normal": [(128, 128, 255, 255)] * 65536,
                "material": [(0, 255, 0, 255)] * 65536}
        for kind, pixels in maps.items():
            path, _sha, fourcc, _dim = material.TEXTURE_TEMPLATES[kind]
            header = (self.output / "template" / path).read_bytes()[:128]
            rebuilt = material.encode_dds(self.width, self.height, pixels, fourcc, header)
            self.assertEqual(rebuilt, (self.output / self.texture_rows[material.TEXTURE_PATHS[kind]]["localFile"]).read_bytes())

    def test_14_fresh_read_only_archive_rebuild(self) -> None:
        if not self.rebuild:
            self.skipTest("Pass --rebuild for a fresh read-only game archive extraction")
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="material_rebuild_") as temporary:
            child = subprocess.run([sys.executable, "-B", str(native.ROOT / "tools" / "prepare_steve_material.py"),
                "--output", temporary, "--cdmw-source", str(self.source), "--deps", str(self.deps),
                "--steve-asset", str(self.steve), "--native-assets", str(self.native_assets),
                "--decoder-python", str(self.decoder_python)], capture_output=True, text=True, timeout=60,
                creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
            self.assertEqual(child.returncode, 0, child.stdout + child.stderr)
            fresh = json.loads((Path(temporary) / "steve-material-report.json").read_text(encoding="utf-8"))
            self.assertEqual(fresh, self.report)
            for name in self.report["files"]:
                self.assertEqual((Path(temporary) / name).read_bytes(), (self.output / name).read_bytes())


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=SteveMaterialChecks.output)
    parser.add_argument("--cdmw-source", type=Path, default=SteveMaterialChecks.source)
    parser.add_argument("--deps", type=Path, default=SteveMaterialChecks.deps)
    parser.add_argument("--steve-asset", type=Path, default=SteveMaterialChecks.steve)
    parser.add_argument("--native-assets", type=Path, default=SteveMaterialChecks.native_assets)
    parser.add_argument("--decoder-python", type=Path, default=SteveMaterialChecks.decoder_python)
    parser.add_argument("--rebuild", action="store_true")
    args = parser.parse_args()
    for key in ("output", "deps", "steve", "native_assets", "decoder_python", "rebuild"):
        setattr(SteveMaterialChecks, key, getattr(args, {"steve": "steve_asset"}.get(key, key)))
    SteveMaterialChecks.source = args.cdmw_source
    result = unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(SteveMaterialChecks))
    raise SystemExit(0 if result.wasSuccessful() else 1)


if __name__ == "__main__":
    main()
