"""Verify offline Steve prefab outputs and refusal paths, without game calls.

--rebuild reads the original game archives again in a clean child process and
requires every generated byte and report field to match the existing output.
"""
from __future__ import annotations

import argparse
import copy
import json
import os
from pathlib import Path
import shutil
import struct
import subprocess
import sys
import tempfile
import unittest

import prepare_native_steve as native
import prepare_steve_material as material
import prepare_steve_prefab as prefab
import prepare_asset_overlay as overlay


class StevePrefabChecks(unittest.TestCase):
    output = native.ROOT / "build/steve-prefab"
    source = native.ROOT / "build/cdmw-fixed-source"
    deps = native.ROOT / "build/cdmw-deps"
    material_report = native.ROOT / "build/steve-material/steve-material-report.json"
    game = None
    rebuild = False

    @classmethod
    def setUpClass(cls):
        native.load_cdmw(cls.source, cls.deps)
        cls.output = native.output_directory(cls.output)
        cls.report = prefab.strict_json((cls.output / prefab.REPORT_NAME).read_bytes())
        cls.original = (cls.output / "template" / prefab.PREFAB_TEMPLATE).read_bytes()
        cls.candidate = (cls.output / "resources" / prefab.PREFAB_PATH).read_bytes()
        cls.descriptor = (cls.output / "resources" / prefab.DESCRIPTOR_PATH).read_bytes()
        cls.input_report = prefab.strict_json(cls.material_report.read_bytes())

    def test_01_pinned_source_and_all_files(self):
        self.assertEqual(self.report["cdmw"]["commit"], native.CDMW_COMMIT)
        self.assertEqual(self.report["cdmw"]["pythonSourceTreeSha256"], native.CDMW_SOURCE_SHA256)
        self.assertEqual(self.report["supportedExeSha256"], native.EXE_SHA256)
        self.assertEqual(self.report["archiveIndexSha256"], prefab.INDEX_SHA256)
        self.assertEqual(native.sha256(self.original), prefab.PREFAB_SHA256)
        for relative, digest in self.report["files"].items():
            self.assertEqual(native.file_hash(self.output / relative), digest)
        self.assertEqual(native.file_hash(self.material_report), self.report["materialReportSha256"])

    def test_02_exact_seven_resources_are_packager_inputs(self):
        resources, payloads, reports = overlay.load_resources([self.output / prefab.REPORT_NAME])
        wanted = set(prefab.INPUT_RESOURCES) | {prefab.PREFAB_PATH, prefab.DESCRIPTOR_PATH}
        self.assertEqual(set(payloads), wanted)
        self.assertEqual(len(resources), 7)
        self.assertEqual(len(reports), 1)
        for row in self.report["candidateResources"]:
            self.assertEqual(row["localFile"], "resources/" + row["virtualPath"])
            self.assertTrue(Path(row["virtualPath"]).name.startswith("crimsonmc_"))
            self.assertNotEqual(row["virtualPath"], row["templatePath"])
            self.assertEqual(row["sha256"], native.sha256(payloads[row["virtualPath"]]))
            self.assertEqual(row["templateArchiveFlags"], self.report["templates"][row["templatePath"]]["archiveFlags"])

    def test_03_complete_structure_and_independent_single_span_comparison(self):
        from cdmw.core.prefab_binary import decode_prefab_binary, walk_is_determined
        source, candidate = decode_prefab_binary(self.original), decode_prefab_binary(self.candidate)
        self.assertTrue(source.walk_complete and candidate.walk_complete)
        self.assertTrue(walk_is_determined(self.original) and walk_is_determined(self.candidate))
        self.assertEqual(len(source.objects), 2)
        self.assertEqual(source.objects[1], candidate.objects[1])
        self.assertEqual(source.types, candidate.types)
        self.assertEqual(source.pointers, candidate.pointers)
        span = source.objects[0].resources[0]
        self.assertEqual(struct.unpack_from("<I", self.original, span.offset)[0], len(native.BODY))
        start, end = span.offset + 4, span.offset + 4 + span.length
        expected = self.original[:start] + material.PAC_PATH.encode() + self.original[end:]
        self.assertEqual(self.candidate, expected)
        self.assertEqual(candidate.objects[0].resources[0].text, material.PAC_PATH)
        self.assertEqual([item.text for item in candidate.all_strings()],
                         [material.PAC_PATH, "Nude", prefab.UNDERWEAR, "Underwear"])

    def test_04_no_edit_and_inverse_rewrite_restore_original_bytes(self):
        from cdmw.core.prefab_binary_edit import rewrite_prefab_paths
        self.assertEqual(rewrite_prefab_paths(self.original, {}).data, self.original)
        reverse = rewrite_prefab_paths(self.candidate, {material.PAC_PATH: native.BODY})
        self.assertEqual(reverse.data, self.original)
        self.assertEqual(reverse.byte_delta, 0)
        self.assertEqual(len(reverse.edits), 1)
        fresh, audit = prefab.build_prefab(self.original)
        self.assertEqual(fresh, self.candidate)
        self.assertEqual(audit, self.report["prefabAudit"])

    def test_05_descriptor_and_real_skeleton_dependencies_are_preserved(self):
        original = (self.output / "template" / native.DESCRIPTOR).read_bytes()
        self.assertEqual(self.descriptor, original)
        self.assertEqual(native.sha256(self.descriptor), prefab.DESCRIPTOR_SHA256)
        self.assertEqual(prefab.audit_descriptor(self.descriptor), self.report["descriptorAudit"])
        for path, digest in prefab.DEPENDENCIES.items():
            self.assertEqual(native.file_hash(self.output / "template" / path), digest)
        self.assertEqual(self.report["logicalPrefabPath"], prefab.LOGICAL_PREFAB)

    def test_06_original_five_material_payloads_are_copied_byte_identically(self):
        for row in self.input_report["candidateResources"]:
            self.assertEqual((self.output / row["localFile"]).read_bytes(),
                             (self.material_report.parent / row["localFile"]).read_bytes())

    def test_07_no_engine_loading_or_controlled_body_claims(self):
        self.assertTrue(self.report["integration"])
        self.assertTrue(all(value is False for value in self.report["integration"].values()))
        self.assertFalse(self.report["prefabAudit"]["controllerSupplied"])
        for word in ("controller", "animation", "Kliff", "Underwear", "PATHC"):
            self.assertTrue(any(word in line for line in self.report["limitations"]), word)

    def test_08_wrong_target_and_source_fingerprint_stop(self):
        for target in (native.BODY, "../steve.pac", "/" + material.PAC_PATH, "character/model/foreign.pac"):
            with self.assertRaisesRegex(ValueError, "reviewed new Steve PAC"):
                prefab.build_prefab(self.original, target)
        with self.assertRaisesRegex(ValueError, "fingerprint"):
            prefab.build_prefab(self.original + b"extra")
        with self.assertRaisesRegex(ValueError, "fingerprint"):
            prefab.audit_descriptor(self.descriptor.replace(b"phm_01.pab", b"phm_02.pab"))

    def test_09_incomplete_structure_and_changed_underwear_are_refused(self):
        from cdmw.core.prefab_binary_edit import rewrite_prefab_paths
        with self.assertRaises(ValueError):
            prefab.audit_prefab(self.original[:-17], native.BODY)
        wrong = rewrite_prefab_paths(self.original, {prefab.UNDERWEAR: prefab.UNDERWEAR.replace("0001", "0002")}).data
        with self.assertRaisesRegex(ValueError, "underwear dependency"):
            prefab.audit_prefab(wrong, native.BODY)

    def material_case(self, change):
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="steve-prefab-input-") as temporary:
            copied = Path(temporary) / "material"
            shutil.copytree(self.material_report.parent, copied)
            report = copy.deepcopy(self.input_report)
            change(report)
            path = copied / self.material_report.name
            path.write_text(json.dumps(report), encoding="utf-8")
            return prefab.load_material(path)

    def test_10_polluted_report_paths_hashes_templates_and_claims_are_refused(self):
        changes = [
            lambda r: r["integration"].update(installed=True),
            lambda r: r.update(supportedExeSha256="0" * 64),
            lambda r: r["cdmw"].update(commit="0" * 40),
            lambda r: r["candidateResources"].append(copy.deepcopy(r["candidateResources"][0])),
            lambda r: r["candidateResources"][0].update(localFile="../escape.dds"),
            lambda r: r["candidateResources"][0].update(virtualPath=native.BODY),
            lambda r: r["candidateResources"][0].update(templateSha256="0" * 64),
            lambda r: r["candidateResources"][0].update(kind="prefab"),
            lambda r: r["candidateResources"][0].update(sha256="0" * 64),
            lambda r: r["files"].update({"../escape.pac": "0" * 64}),
            lambda r: r["candidateResources"].__setitem__(1, copy.deepcopy(r["candidateResources"][0])),
        ]
        for change in changes:
            with self.subTest(change=changes.index(change)):
                with self.assertRaises(ValueError):
                    self.material_case(change)

    def test_11_duplicate_json_keys_and_nonfinite_values_are_refused(self):
        for raw in (b'{"candidateResources":[],"candidateResources":[1]}', b'{"x":NaN}', b'[]'):
            with self.assertRaises(ValueError):
                prefab.strict_json(raw)

    def test_12_changed_payload_is_rejected_before_publication(self):
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="steve-prefab-corrupt-") as temporary:
            copied = Path(temporary) / "material"
            shutil.copytree(self.material_report.parent, copied)
            path = copied / self.input_report["candidateResources"][0]["localFile"]
            path.write_bytes(path.read_bytes()[:-1])
            with self.assertRaisesRegex(ValueError, "checksum"):
                prefab.load_material(copied / self.material_report.name)

    def test_13_output_traversal_collisions_and_report_protection(self):
        with self.assertRaises(ValueError):
            prefab.preflight(native.ROOT / "artifacts/steve", [prefab.REPORT_NAME])
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="steve-prefab-output-") as temporary:
            output = Path(temporary)
            with self.assertRaises(ValueError):
                prefab.publish(output, {"../outside.pac": b"bad"}, {})
            self.assertEqual(list(output.iterdir()), [])
            (output / prefab.REPORT_NAME).mkdir()
            with self.assertRaisesRegex(ValueError, "occupied"):
                prefab.publish(output, {"resources/first.pac": b"must not be written"}, {})
            self.assertFalse((output / "resources").exists())
            (output / prefab.REPORT_NAME).rmdir()
            (output / (prefab.REPORT_NAME + ".tmp")).write_bytes(b"foreign temporary")
            with self.assertRaisesRegex(ValueError, "occupied"):
                prefab.publish(output, {"resources/first.pac": b"must not be written"}, {})
            self.assertEqual((output / (prefab.REPORT_NAME + ".tmp")).read_bytes(), b"foreign temporary")

    def test_14_real_directory_links_are_refused_for_input_and_output(self):
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="steve-prefab-link-") as temporary:
            parent = Path(temporary)
            alias = parent / "alias"
            destination = self.material_report.parent
            if os.name == "nt":
                subprocess.run(["cmd", "/c", "mklink", "/J", str(alias), str(destination)],
                               check=True, capture_output=True, creationflags=subprocess.CREATE_NO_WINDOW)
            else:
                alias.symlink_to(destination, target_is_directory=True)
            try:
                with self.assertRaisesRegex(ValueError, "symlinks or junctions"):
                    prefab.load_material(alias / self.material_report.name)
                with self.assertRaisesRegex(ValueError, "symlinks or junctions"):
                    prefab.publish(alias / "new-output", {"resources/item.pac": b"bad"}, {})
            finally:
                alias.unlink() if alias.is_symlink() else alias.rmdir()

    def test_15_output_cannot_overlap_inputs_or_fixed_source(self):
        cases = ((self.material_report.parent, "separate"),
                 (self.source / "outputs", "overlaps"),
                 (self.source.parent, "ignored build subdirectory"))
        for output, reason in cases:
            with self.assertRaisesRegex(ValueError, reason):
                prefab.prepare(Path("unused"), output, self.source, self.deps, self.material_report)

    def test_16_fresh_readonly_archive_rebuild_is_byte_identical(self):
        if not self.rebuild:
            self.skipTest("Pass --rebuild to reread the real archives")
        with tempfile.TemporaryDirectory(dir=native.ROOT / "build", prefix="steve-prefab-rebuild-") as temporary:
            command = [sys.executable, "-B", str(native.ROOT / "tools/prepare_steve_prefab.py"),
                "--output", temporary, "--material-report", str(self.material_report),
                "--cdmw-source", str(self.source), "--deps", str(self.deps)]
            if self.game is not None:
                command.extend(("--game-root", str(self.game)))
            result = subprocess.run(command, capture_output=True, text=True, timeout=120,
                                    creationflags=getattr(subprocess, "CREATE_NO_WINDOW", 0))
            self.assertEqual(result.returncode, 0, result.stdout + result.stderr)
            fresh = prefab.strict_json((Path(temporary) / prefab.REPORT_NAME).read_bytes())
            self.assertEqual(fresh, self.report)
            for relative in self.report["files"]:
                self.assertEqual((Path(temporary) / relative).read_bytes(), (self.output / relative).read_bytes())


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=StevePrefabChecks.output)
    parser.add_argument("--material-report", type=Path, default=StevePrefabChecks.material_report)
    parser.add_argument("--cdmw-source", type=Path, default=StevePrefabChecks.source)
    parser.add_argument("--deps", type=Path, default=StevePrefabChecks.deps)
    parser.add_argument("--game-root", type=Path)
    parser.add_argument("--rebuild", action="store_true")
    args = parser.parse_args()
    for name, argument in (("output", "output"), ("material_report", "material_report"),
                           ("source", "cdmw_source"), ("deps", "deps"), ("game", "game_root"), ("rebuild", "rebuild")):
        setattr(StevePrefabChecks, name, getattr(args, argument))
    result = unittest.TextTestRunner(verbosity=2).run(unittest.defaultTestLoader.loadTestsFromTestCase(StevePrefabChecks))
    raise SystemExit(0 if result.wasSuccessful() else 1)


if __name__ == "__main__":
    main()
